NEW: automatically create release

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,4 @@
-name: Conan Build
+name: Build
 on:
   push:
     branches:
@@ -6,6 +6,8 @@ on:
       - develop
       - release-*
       - feat-*
+    tags:
+      - v2.*
 
 env:
   QT_VERSION_MAJOR: 5
@@ -151,3 +153,48 @@ jobs:
         with:
           name: MacOS_Dist
           path: _build/package/dist
+
+  release:
+    needs: [build_linux, build_windows, build_macos]
+    runs-on: ubuntu-latest
+    if: contains(github.ref, 'refs/tags/v')
+    steps:
+      - uses: actions/checkout@v1
+      - name: Download pre-built packages for Linux
+        uses: actions/download-artifact@v1
+        with:
+          name: Linux_Dist
+          path: artifacts
+      - name: Download pre-built packages for Windows
+        uses: actions/download-artifact@v1
+        with:
+          name: Windows_Dist
+          path: artifacts
+      - name: Download pre-built packages for MacOS
+        uses: actions/download-artifact@v1
+        with:
+          name: MacOS_Dist
+          path: artifacts
+      - name: Create Release Notes
+        id: release_notes
+        run: |
+          version=$(printf '${{ github.ref }}' | sed -E 's#refs/tags/v(.*)#\1#')
+          notes_zh="dist/changes-${version}-zh-CN.md"
+          [[ -f "${notes_zh}" ]] || { echo >&2 "release notes is required."; exit 1; }
+          notes_en="dist/changes-${version}-en-US.md"
+          [[ -f "${notes_en}" ]] || { echo >&2 "release notes is required."; exit 1; }
+          content=$(cat ${notes_zh} | sed '1d')
+          content="${content}\n\n---\n\n$(cat ${notes_en} | sed '1d')"
+          printf "${content}\n" > dist/changes-${version}.md
+          echo "::set-output name=version::${version}"
+          echo "::set-output name=content_file::dist/changes-${version}.md"
+      - name: Create Release
+        id: create_release
+        uses: ncipollo/release-action@v1
+        with:
+          name: WizNotePlus v${{ steps.release_notes.outputs.version }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+          artifacts: "artifacts/*"
+          bodyFile: ${{ steps.release_notes.outputs.content_file }}
+          draft: true
+          prerelease: true
